#!/usr/bin/env python3
"""
Ralph Loop Archivist Tool
Promotes files from dev/ to prod/ and rebuilds living docs.
"""

import os
import sys
import shutil
import argparse
from pathlib import Path

def promote_file(src_path, dst_path):
    """Copies a file from dev to prod."""
    dst_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src_path, dst_path)
    print(f"Promoted: {src_path} -> {dst_path}")
    return True

def rebuild_docs(prod_dir):
    """Rebuilds living docs in prod/docs/."""
    docs_dir = Path(prod_dir) / 'docs'
    docs_dir.mkdir(parents=True, exist_ok=True)
    
    # Simple index rebuild
    index_path = docs_dir / 'index.md'
    with open(index_path, 'w', encoding='utf-8') as f:
        f.write("# Ralph Loop Production Index\n\n")
        f.write("This file is auto-generated by the Archivist.\n\n")
        
    # Scan prod/library for notes
    library_dir = Path(prod_dir) / 'library'
    if library_dir.exists():
        notes = list(library_dir.rglob('*.md'))
        f.write(f"\n## Notes ({len(notes)} files)\n\n")
        for note in notes:
            rel_path = note.relative_to(prod_dir)
            f.write(f"- [{rel_path}]({rel_path})\n")
            
    print(f"Rebuilt docs in {docs_dir}")

def promote_directory(src_dir, dst_dir):
    """Copies a directory tree."""
    src = Path(src_dir)
    dst = Path(dst_dir)
    
    if not src.exists():
        print(f"Source directory {src} does not exist.")
        return False
        
    dst.mkdir(parents=True, exist_ok=True)
    
    for file_path in src.rglob('*'):
        if file_path.is_file():
            rel_path = file_path.relative_to(src)
            dst_file = dst / rel_path
            promote_file(file_path, dst_file)
            
    return True

def main():
    parser = argparse.ArgumentParser(description='Ralph Loop Archivist Tool')
    parser.add_argument('--promote', type=str, help='Promote a specific file or directory from dev to prod')
    parser.add_argument('--rebuild', action='store_true', help='Rebuild living docs')
    args = parser.parse_args()
    
    prod_dir = Path('prod')
    
    if args.promote:
        src = Path(args.promote)
        if not src.exists():
            print(f"Error: Source {src} does not exist.")
            sys.exit(1)
            
        if src.is_file():
            dst = prod_dir / src.relative_to('dev')
            promote_file(src, dst)
        elif src.is_dir():
            dst = prod_dir / src.relative_to('dev')
            promote_directory(src, dst)
            
    if args.rebuild:
        rebuild_docs(prod_dir)
        
    if not args.promote and not args.rebuild:
        parser.print_help()
        sys.exit(1)

if __name__ == '__main__':
    main()
