#!/usr/bin/env pwsh
# Run Library Science audit and recommendations
# Usage: ./library_scientist.ps1

param(
    [string]$Dir = "dev/library"
)

$WORKSPACE = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot "..\.."))
$targetDir = Join-Path $WORKSPACE $Dir

if (-not (Test-Path $targetDir)) {
    Write-Error "Directory $targetDir does not exist."
    exit 1
}

function Parse-YamlFrontMatter($filePath) {
    try {
        $content = Get-Content -Raw -Path $filePath -Encoding utf8
        if ($content -match "^(?:\r?\n)*---\r?\n([\s\S]*?)\r?\n---") {
            $yamlText = $Matches[1]
            $metadata = @{}
            $lines = $yamlText -split "\r?\n"
            foreach ($line in $lines) {
                $line = $line.Trim()
                if ($line.StartsWith("#") -or -not $line) { continue }
                if ($line -match "^([^:]+):(.*)$") {
                    $metadata[$Matches[1].Trim()] = $Matches[2].Trim().Trim('"', "'")
                }
            }
            return $metadata
        }
    } catch {}
    return $null
}

$allNotes = @{}
$typeCounts = @{}
$tagCounts = @{}
$statusCounts = @{}
$orphans = @()

$files = Get-ChildItem -Path $targetDir -Filter "*.md" -Recurse

# Pass 1: Parse metadata
foreach ($file in $files) {
    $relPath = $file.FullName.Substring($WORKSPACE.Length + 1).Replace("\", "/")
    
    if ($relPath.EndsWith("/index.md") -or $relPath.EndsWith("/library_science_audit.md")) {
        continue
    }
    
    $metadata = Parse-YamlFrontMatter $file.FullName
    if (-not $metadata) { continue }
    
    $noteType = ($metadata["type"] ? $metadata["type"] : "unknown")
    $status = ($metadata["status"] ? $metadata["status"] : "draft")
    
    $tags = @()
    $rawTags = $metadata["tags"]
    if ($rawTags -like "[*]") {
        $listVals = $rawTags.Trim('[', ']') -split ","
        foreach ($v in $listVals) { $tags += $v.Trim() }
    } elseif ($rawTags) {
        $tags += $rawTags
    }
    
    $allNotes[$relPath] = @{
        title         = ($metadata["title"] ? $metadata["title"] : $file.BaseName)
        type          = $noteType
        tags          = $tags
        status        = $status
        links         = @()
        backlinkCount = 0
    }
    
    # Counts
    $typeCounts[$noteType] = ($typeCounts[$noteType] ? $typeCounts[$noteType] : 0) + 1
    $statusCounts[$status] = ($statusCounts[$status] ? $statusCounts[$status] : 0) + 1
    foreach ($t in $tags) {
        $tagCounts[$t] = ($tagCounts[$t] ? $tagCounts[$t] : 0) + 1
    }
}

# Pass 2: Map links
foreach ($key in $allNotes.Keys) {
    $noteInfo = $allNotes[$key]
    $content = Get-Content -Raw -Path (Join-Path $WORKSPACE $key)
    
    $foundLinks = [regex]::Matches($content, '\]\((?:file:///)?([^\)]+\.md)\)')
    foreach ($fl in $foundLinks) {
        $linkClean = ($fl.Groups[1].Value -split "#")[0].Trim()
        $targetPosix = $linkClean
        
        if (-not ($targetPosix.StartsWith("dev/") -or $targetPosix.StartsWith("prod/"))) {
            $noteDir = Split-Path $key
            $targetPathResolved = [System.IO.Path]::GetFullPath((Join-Path $WORKSPACE (Join-Path $noteDir $targetPosix)))
            try {
                $targetPosix = $targetPathResolved.Substring($WORKSPACE.Length + 1).Replace("\", "/")
            } catch { continue }
        }
        
        if ($allNotes.ContainsKey($targetPosix)) {
            $noteInfo.links += $targetPosix
            $allNotes[$targetPosix].backlinkCount++
        }
    }
}

# Find Orphans
foreach ($key in $allNotes.Keys) {
    $noteInfo = $allNotes[$key]
    if ($noteInfo.links.Count -eq 0 -and $noteInfo.backlinkCount -eq 0) {
        $orphans += $key
    }
}

# Write Audit Report
$reportFile = Join-Path $targetDir "library_science_audit.md"

$md = @()
$md += "---"
$md += "id: `"library_science_audit`""
$md += "title: `"Library Science Audit & Taxonomy Report`""
$md += "type: `"system_doc`""
$md += "tags: [`"audit`", `"taxonomy`", `"metrics`", `"system`"]"
$md += "status: `"stable`""
$md += "summary: `"Automated structural audit report analyzing library document type density, links, and proposed hybrid system evolutions.`""
$md += "---"
$md += "`n# Library Science Audit & Taxonomy Report`n"
$md += "*Generated by ``library_scientist.ps1`` to drive taxonomical self-evolution.*`n"
$md += "## 📈 Core Library Metrics"
$md += "- **Total Library Documents**: $($allNotes.Keys.Count)"
$md += "- **Orphan Notes (Disconnected)**: $($orphans.Count)"
$md += ""

$md += "### Note Type Distribution"
foreach ($ntype in ($typeCounts.Keys | Sort-Object { $typeCounts[$_] } -Descending)) {
    $md += "- **$($ntype.ToUpper())**: $($typeCounts[$ntype]) notes"
}
$md += ""

$md += "### Note Status Distribution"
foreach ($stat in ($statusCounts.Keys | Sort-Object { $statusCounts[$_] } -Descending)) {
    $md += "- **$($stat.Substring(0,1).ToUpper() + $stat.Substring(1))**: $($statusCounts[$stat]) notes"
}
$md += ""

$md += "## 🔬 Taxonomical Recommendations & Evolution Planner"

# Processing pipeline
$rawAndDrafts = @()
foreach ($key in $allNotes.Keys) {
    if ($allNotes[$key].status -eq "raw" -or $allNotes[$key].status -eq "draft") {
        $rawAndDrafts += $key
    }
}

if ($rawAndDrafts.Count -gt 0) {
    $md += "### 📥 Processing Pipeline (Brain Dumps & Drafts)"
    $md += "The following nodes are raw/draft state and require synthesis or expansion:"
    $limit = [Math]::Min($rawAndDrafts.Count, 5)
    for ($i = 0; $i -lt $limit; $i++) {
        $p = $rawAndDrafts[$i]
        $info = $allNotes[$p]
        $md += "- **[$($info.title)](file:///$($WORKSPACE.Replace('\','/'))/$p)** (status: $($info.status)) -> Propose Zettelkasten decomposition."
    }
    if ($rawAndDrafts.Count -gt 5) {
        $md += "- *... and $($rawAndDrafts.Count - 5) more files.*"
    }
    $md += ""
}

$md += "### 🔀 Structural Hybridization Ideas"
if ($typeCounts.ContainsKey("zettelkasten") -and $typeCounts.ContainsKey("diwk")) {
    $md += "- **Zettelkasten + DIKW Hybridization**: We possess both atomic Zettelkasten files and structured DIKW analysis briefs. Recommendation: Create Zettelkasten notes that contain explicit pointers to high-level Wisdom entries, establishing a directional pathway from raw notes to corporate decision briefs."
} else {
    $md += "- **Taxonomy Expansion**: Recommend introducing more Zettelkasten atomic nodes to link together research papers and brain dump logs."
}

if ($orphans.Count -gt 0) {
    $md += "`n### ⚠️ Orphan Cleanup Required"
    $md += "The following notes have no incoming or outgoing connections. They are conceptually isolated:"
    foreach ($o in $orphans) {
        $md += "- **[$($allNotes[$o].title)](file:///$($WORKSPACE.Replace('\','/'))/$o)**"
    }
}

$md -join "`n" | Set-Content -Path $reportFile -Encoding utf8
Write-Host "Library Scientist: Generated audit report at dev/library/library_science_audit.md" -ForegroundColor Green
