#!/usr/bin/env python3
import os
import sys
import json
import re
from pathlib import Path

# Configure centralized logging
_SCRIPT_DIR = Path(__file__).parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))
from logging_setup import configure_logging
configure_logging(script_name=Path(__file__).name)
import logging
logger = logging.getLogger(__name__)

def parse_yaml_front_matter(file_path):
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()
        match = re.match(r"^---\r?\n([\s\S]*?)\r?\n---", content)
        if not match:
            return None
        
        yaml_text = match.group(1)
        metadata = {}
        for line in yaml_text.splitlines():
            line = line.strip()
            if not line or line.startswith("#") or ":" not in line:
                continue
            key, val = line.split(":", 1)
            metadata[key.strip()] = val.strip().strip('"').strip("'")
        return metadata
    except Exception:
        return None

def analyze_library(library_dir, workspace):
    if not library_dir.exists():
        logger.error("Library Scientist Error: Library directory does not exist.")
        return
        
    all_notes = {}
    type_counts = {}
    tag_counts = {}
    status_counts = {}
    orphans = []
    
    # 1. Parse all notes metadata
    for root, _, files in os.walk(library_dir):
        for file in files:
            if not file.endswith(".md"):
                continue
            
            file_path = Path(root) / file
            rel_path = file_path.relative_to(workspace)
            posix_path = str(rel_path).replace("\\", "/")
            
            if posix_path.endswith("/index.md") or posix_path.endswith("/library_science_audit.md"):
                continue
                
            metadata = parse_yaml_front_matter(file_path)
            if not metadata:
                continue
                
            note_type = metadata.get("type", "unknown")
            status = metadata.get("status", "draft")
            tags = []
            
            # Simple list parser for tags if they are in brackets
            raw_tags = metadata.get("tags", "")
            if raw_tags.startswith("[") and raw_tags.endswith("]"):
                tags = [t.strip().strip('"').strip("'") for t in raw_tags[1:-1].split(",") if t.strip()]
            elif isinstance(raw_tags, list):
                tags = raw_tags
            elif raw_tags:
                tags = [raw_tags]
                
            all_notes[posix_path] = {
                "title": metadata.get("title", file_path.stem),
                "type": note_type,
                "tags": tags,
                "status": status,
                "links": [],
                "backlink_count": 0
            }
            
            type_counts[note_type] = type_counts.get(note_type, 0) + 1
            status_counts[status] = status_counts.get(status, 0) + 1
            for t in tags:
                tag_counts[t] = tag_counts.get(t, 0) + 1

    # 2. Map links to find orphans and link densities
    for posix_path, data in all_notes.items():
        try:
            with open(workspace / posix_path, "r", encoding="utf-8") as f:
                content = f.read()
        except Exception:
            continue
            
        found_links = re.findall(r"\]\((?:file:///)?([^\)]+\.md)\)", content)
        for link in found_links:
            link_clean = link.split("#")[0].strip()
            target_posix = link_clean
            
            if not target_posix.startswith("dev/") and not target_posix.startswith("prod/"):
                note_dir = Path(posix_path).parent
                target_path = (workspace / note_dir / target_posix).resolve()
                try:
                    target_posix = str(target_path.relative_to(workspace)).replace("\\", "/")
                except Exception:
                    continue
            
            if target_posix in all_notes:
                data["links"].append(target_posix)
                all_notes[target_posix]["backlink_count"] += 1

    # Detect orphans
    for posix_path, data in all_notes.items():
        if len(data["links"]) == 0 and data["backlink_count"] == 0:
            orphans.append(posix_path)
            
    # 3. Generate Library Science Audit report
    report_path = library_dir / "library_science_audit.md"
    
    md = []
    md.append("---")
    md.append("id: \"library_science_audit\"")
    md.append("title: \"Library Science Audit & Taxonomy Report\"")
    md.append("type: \"system_doc\"")
    md.append("tags: [\"audit\", \"taxonomy\", \"metrics\", \"system\"]")
    md.append("status: \"stable\"")
    md.append("summary: \"Automated structural audit report analyzing library document type density, links, and proposed hybrid system evolutions.\"")
    md.append("---")
    md.append("\n# Library Science Audit & Taxonomy Report\n")
    md.append("*Generated by `library_scientist.py` to drive taxonomical self-evolution.*\n")
    
    md.append("## 📈 Core Library Metrics")
    md.append(f"- **Total Library Documents**: {len(all_notes)}")
    md.append(f"- **Orphan Notes (Disconnected)**: {len(orphans)}")
    md.append("")
    
    md.append("### Note Type Distribution")
    for ntype, count in sorted(type_counts.items(), key=lambda x: x[1], reverse=True):
        md.append(f"- **{ntype.upper()}**: {count} notes")
    md.append("")
    
    md.append("### Note Status Distribution")
    for stat, count in sorted(status_counts.items(), key=lambda x: x[1], reverse=True):
        md.append(f"- **{stat.capitalize()}**: {count} notes")
    md.append("")

    # 4. Synthesizer / Recommender Brainstorming
    md.append("## 🔬 Taxonomical Recommendations & Evolution Planner")
    
    # Check for raw items (Brain Dumps or Drafts)
    raw_and_drafts = [p for p, d in all_notes.items() if d["status"] in ["raw", "draft"]]
    if raw_and_drafts:
        md.append("### 📥 Processing Pipeline (Brain Dumps & Drafts)")
        md.append("The following nodes are raw/draft state and require synthesis or expansion:")
        for r in raw_and_drafts[:5]:
            info = all_notes[r]
            md.append(f"- **[{info['title']}](file:///{workspace.as_posix()}/{r})** (status: {info['status']}) -> Propose Zettelkasten decomposition.")
        if len(raw_and_drafts) > 5:
            md.append(f"- *... and {len(raw_and_drafts) - 5} more files.*")
        md.append("")
        
    # Analyze Tag Overlaps and Note Type clusters for creative hybridization suggestions
    md.append("### 🔀 Structural Hybridization Ideas")
    has_suggestions = False
    
    # 1. Zettelkasten + DIKW
    if type_counts.get("zettelkasten", 0) > 0 and type_counts.get("diwk", 0) > 0:
        md.append("- **Zettelkasten & DIKW Hybridization**: Leverage atomic Zettelkasten files as baseline factual/observational elements, and map them to structured DIKW briefs. Recommendation: Embed direct hyperlinks from atomic concept nodes to high-level Wisdom entries to build a clear directional pathway from raw facts to systemic insights.")
        has_suggestions = True
        
    # 2. SOAP + SDLC Project
    if type_counts.get("soap", 0) > 0 and type_counts.get("sdlc_project", 0) > 0:
        md.append("- **SOAP & SDLC Project Hybridization**: Apply the SOAP (Subjective, Objective, Assessment, Plan) model within SDLC Project sprint logs. Recommendation: Use Subjective/Objective sections to capture team feedback and raw telemetry, Assessment to evaluate software health, and Plan to update the roadmap backlog.")
        has_suggestions = True
        
    # 3. Cornell + Feynman
    if type_counts.get("cornell", 0) > 0 and type_counts.get("feynman", 0) > 0:
        md.append("- **Cornell & Feynman Hybridization**: Combine Cornell's retrieval cues with the Feynman technique. Recommendation: Write a Feynman explanation (simplifying a complex topic for a child) in the main notes column, and place questions or keywords in the cue column to maximize study/retrieval efficiency.")
        has_suggestions = True
        
    # 4. Zettelkasten + Concept Map
    if type_counts.get("zettelkasten", 0) > 0 and type_counts.get("concept_map", 0) > 0:
        md.append("- **Zettelkasten & Concept Map Hybridization**: Link atomic concepts to topological structures. Recommendation: Create a Concept Map node that acts as a structural schema, linking multiple atomic Zettelkasten notes together to model complex, multi-variable relationships.")
        has_suggestions = True
        
    # 5. QEC + Eisenhower
    if type_counts.get("qec", 0) > 0 and type_counts.get("eisenhower", 0) > 0:
        md.append("- **QEC & Eisenhower Hybridization**: Bridge logical argumentation with task prioritization. Recommendation: Map QEC (Question-Evidence-Conclusion) conclusions directly to Eisenhower priority matrices to convert conceptual answers into immediate, structured tasks.")
        has_suggestions = True
        
    # 6. Brain Dump processing fallback
    if type_counts.get("brain_dump", 0) > 0:
        md.append("- **Brain Dump Decomposition**: We have unprocessed raw ideas. Recommendation: Decompose the atomic ideas inside active Brain Dumps into individual Zettelkasten concepts or compile them into a DIKW synthesis brief.")
        has_suggestions = True

    if not has_suggestions:
        md.append("- **Taxonomy Expansion**: Propose creating new templates and introducing a mix of Zettelkasten (atomic concepts), DIKW (structured synthesis), and SOAP (analytical logs) to map knowledge and software features.")
        
    # Warn about orphans
    if orphans:
        md.append("\n### ⚠️ Orphan Cleanup Required")
        md.append("The following notes have no incoming or outgoing connections. They are conceptually isolated:")
        for o in orphans:
            md.append(f"- **[{all_notes[o]['title']}](file:///{workspace.as_posix()}/{o})**")
            
    with open(report_path, "w", encoding="utf-8") as f:
        f.write("\n".join(md))
        
    logger.info(f"Library Scientist: Generated audit report at {report_path.relative_to(workspace)}")

def main():
    import argparse
    parser = argparse.ArgumentParser(description="Run Library Science audit and recommendations.")
    parser.add_argument("--dir", type=str, default="dev/library", help="Directory to analyze (dev/library or prod/library)")
    
    args = parser.parse_args()
    workspace = Path(__file__).parent.parent.parent.resolve()
    target_dir = (workspace / args.dir).resolve()
    
    try:
        analyze_library(target_dir, workspace)
    except Exception:
        logger.exception("Unhandled exception in library_scientist.py")
        sys.exit(1)

if __name__ == "__main__":
    main()
